openapi: 3.1.0
info:
  title: Amiqus ID REST API
  version: '2.0'
  description: |
    Amiqus ID API reference.

    🚧 Please note this documentation is beta and is subject to change without notice.

    [Changelog](/changelog)
  contact:
    email: developers@amiqus.co
    name: Amiqus Engineering
    url: 'https://developers.amiqus.co/aqid/api-reference.html'
servers:
  - url: 'https://amiqusid.test/api/v2'
    description: Local
  - url: 'https://id.amiqus.co/api/v2'
    description: Production
  - url: 'https://stage.aqid.co/api/v2'
    description: Stage
  - url: 'https://amiqusid.test/api'
    description: Local v1
tags:
  - name: Service Status
  - name: User Account
  - name: Your Team
  - name: Records
  - name: Record Assignees
  - name: Clients
  - name: Client Assignees
  - name: Client Organisations
  - name: Steps
  - name: Teams
  - name: Organisations
  - name: Documents
  - name: Templates
  - name: Webhooks
  - name: Forms
  - name: Other Resources
paths:
  /status:
    $ref: ./paths/status.yaml
  /me:
    $ref: ./paths/me.yaml
  /me/teams:
    $ref: ./paths/me@teams.yaml
  /team:
    $ref: ./paths/team.yaml
  /team/me:
    $ref: ./paths/team@me.yaml
  /team/members:
    $ref: ./paths/team@members.yaml
  /clients:
    $ref: ./paths/clients.yaml
  /clients/{id}:
    $ref: ./paths/clients@{id}.yaml
  /clients/{id}/address:
    $ref: ./paths/clients@{id}@address.yaml
  /clients/{id}/assignees:
    $ref: ./paths/clients@{id}@assignees.yaml
  /clients/{clientId}/assignees/{assigneeId}:
    $ref: ./paths/clients@{clientId}@assignees@{assigneeId}.yaml
  /clients/{id}/organisations:
    $ref: ./paths/clients@{id}@organisations.yaml
  /clients/{clientId}/organisations/{organisationId}:
    $ref: ./paths/clients@{clientId}@organisations@{organisationId}.yaml
  /clients/{id}/forms:
    $ref: ./paths/clients@{id}@forms.yaml
  /clients/{id}/forms/{reference}:
    $ref: ./paths/clients@{id}@forms@{reference}.yaml
  /clients/{id}/forms/{reference}/download:
    $ref: ./paths/clients@{id}@forms@{reference}@download.yaml
  /clients/{id}/records:
    $ref: ./paths/clients@{id}@records.yaml
  /clients/{id}/files:
    $ref: ./paths/clients@{id}@files.yaml
  /clients/{clientId}/files/{fileId}/download:
    $ref: ./paths/clients@{clientId}@files@{fileId}@download.yaml
  /organisations:
    $ref: ./paths/organisations.yaml
  /organisations/{id}:
    $ref: ./paths/organisations@{id}.yaml
  /records:
    $ref: ./paths/records.yaml
  /records/{id}:
    $ref: ./paths/records@{id}.yaml
  /records/{id}/archive:
    $ref: ./paths/records@{id}@archive.yaml
  /records/{id}/expire:
    $ref: ./paths/records@{id}@expire.yaml
  /records/{id}/download:
    $ref: ./paths/records@{id}@download.yaml
  /records/{id}/steps:
    $ref: ./paths/records@{id}@steps.yaml
  /records/{id}/documents:
    $ref: ./paths/records@{id}@documents.yaml
  /records/{id}/assignees:
    $ref: ./paths/records@{id}@assignees.yaml
  /records/{recordId}/assignees/{assigneeId}:
    $ref: ./paths/records@{recordId}@assignees@{assigneeId}.yaml
  /teams/{teamId}/members:
    $ref: ./paths/teams@{teamId}@members.yaml
  /teams/{teamId}/members/{teamMemberId}:
    $ref: ./paths/teams@{teamId}@members@{teamMemberId}.yaml
  /documents:
    $ref: ./paths/documents.yaml
  /templates/emails:
    $ref: ./paths/templates@emails.yaml
  /templates/documents:
    $ref: ./paths/templates@documents.yaml
  /templates/records:
    $ref: ./paths/templates@records.yaml
  /webhooks:
    $ref: ./paths/webhooks.yaml
  /webhooks/{id}:
    $ref: ./paths/webhooks@{id}.yaml
  /webhooks/{id}/deliveries:
    $ref: ./paths/webhooks@{id}@deliveries.yaml
  /forms:
    $ref: ./paths/forms.yaml
  /forms/{reference}:
    $ref: ./paths/forms@{reference}.yaml
  /steps:
    $ref: ./paths/steps.yaml
  /attachments:
    $ref: ./paths/attachments.yaml
  /sdk_token:
    $ref: ./paths/sdk_token.yaml
components:
  schemas: {}
  securitySchemes:
    personal_token:
      bearerFormat: auth-scheme
      description: Bearer HTTP authentication.
      scheme: bearer
      type: http
    oauth:
      type: oauth2
      description: OAuth2 authentication.
      flows:
        authorizationCode:
          authorizationUrl: /oauth/authorize
          tokenUrl: /oauth/token
          refreshUrl: /oauth/token
          scopes: {}
